### ISSUE TITLE
Invalid Icon in Prefab 

### ISSUE THREAD

**Issue by MarzV** [bettyblocks/material-ui-component-set#1339]
Hey BB guys,
did an update on the Material UI set and did update of the cli to version 23.48.0

I got a an error that chosen Icon in Prefab is invalid.
![image](https://user-images.githubusercontent.com/18568753/128465965-09987466-fc87-4da8-af2c-760d8460ed57.png)

**Comment by jeroenreijs** [comment]
I notice the message `update available from 23.45.0 to 23.48.0` which means although you might think you updated the CLI, you are actually running an older version. Try and see what running `yarn` can do for you. It should install the latest packages. Then try building it again.
