### ISSUE TITLE
Error when running npm run dev

### ISSUE THREAD

**Issue by MarzV** [bettyblocks/material-ui-component-set#357]
Hey Guys,

Working on a windows 10 machine latest version machine, 
node version v14.5
BB -V: 23.5

I have a problem running the development script, npm run dev, when I run the command I get this form the terminal:
[nodemon] 1.19.4
[nodemon] to restart at any time, enter `rs`
[nodemon] watching dir(s): src\**\*
[nodemon] watching extensions: js,mjs,json
[nodemon] starting `'yarn build`
**''yarn' is not recognized as an internal or external command,**

The dev script in package.json looks like this: **"dev": "nodemon --watch src --exec 'yarn build && yarn start'",**
The dev script from the hello-world repo, that works just fine look like this: **"dev": "nodemon --watch src --exec \"rimraf dist && bb components build && bb components serve\"",**

So I replaced the dev script from material repo with the one in the hello-world repo, and now the error **''yarn' is not recognized as an internal or external command,** is not there anymore,;-)

BUT now I get next error message:

[nodemon] 1.19.4
[nodemon] to restart at any time, enter `rs`
[nodemon] watching dir(s): src\**\*
[nodemon] watching extensions: js,mjs,json
[nodemon] starting `rimraf dist && bb components build && bb components serve`

**SyntaxError in alert.js: Unexpected token ) in JSON at position 49**

[nodemon] app crashed - waiting for file changes before starting...

I think that this has something to do with the fact that I am using a Windows machine?. And this repo is not updated with the same building setup that is used in the hello-world repo, because that is just working fine. 

Can you please try to help me with an update on the dev script and the generating of the JSON file that can be used on a windows machine so I can use the material-design components in my bettyblocks applications

Kind regards,
Marcel from Holygrow

**Comment by jeroenreijs** [comment]
Hi Marcel, this is a know bug. And the reason is because you're using Windows indeed.
We don't have a solution just yet, but if we do, we'll let you know here.

**Comment by roy-willemse** [comment]
@jeroenreijs @MarzV I had the same issue, if you use this dev script it'll work. Not sure if this fixes your second error: "Unexpected token ) in JSON at position 49", I think this is because of a specific version of the CLI.

`"dev": "nodemon --watch src --exec \"yarn build && yarn start\"",`

Escaping the string seems to solve the issue for windows

**Comment by nulian** [comment]
This will be fixed in #505 and will be soon released.
