### ISSUE TITLE
Autocomplete 'Clear' interaction function doesn't work.

### ISSUE THREAD

**Issue by JorisPannekeet** [bettyblocks/material-ui-component-set#831]
As the title says.
I'm unable/don't have time to look into it myself so im posting it here :)

Usecase: clear an autocomplete field on formSuccess.
Usecase2: Clear an autocomplete field on button click.

**Comment by jeroenreijs** [comment]
I have created a ticket for this in which we will investigate and solve the issue. https://bettyblocks.atlassian.net/browse/TA-2224
