### ISSUE TITLE
Tab crashes runtime if you use a var in the title label 

### ISSUE THREAD

**Issue by MarcelKorporaal** [bettyblocks/material-ui-component-set#928]
Error: Minified React error #321; visit https://reactjs.org/docs/error-decoder.html?invariant=321
Invalid Hook Call
![image](https://user-images.githubusercontent.com/56920518/108198306-c1897980-711b-11eb-9dd9-bb6d7b71f4a4.png)

Tried to look if it was a easy fix to do myself but didnt see the solution

**Comment by BarryBlocks** [comment]
Thanks Marcel! A bug ticket is created on the Governators backlog: https://bettyblocks.atlassian.net/browse/TA-2310
