### ISSUE TITLE
File upload input cannot be set to required

### ISSUE THREAD

**Issue by MarcelKorporaal** [bettyblocks/material-ui-component-set#957]
When you toggle the required option on and later return to the options, the box is unticked again.
See: https://i.gyazo.com/e9f79ebe4bc72a004a13916af1ad3e86.gif 
This also means that my front end validation does not work

**Comment by jeroenreijs** [comment]
The required validation only works for form fields which are connected to a property. A custom model attribute is then created and inherits the validation of the property. When not connected to a property, checking the required checkbox has no use.
