### ISSUE TITLE
DateTimePicker's hidden input defaults to current datetime if left empty.

### ISSUE THREAD

**Issue by MarcelKorporaal** [bettyblocks/material-ui-component-set#975]
Components settings: https://i.gyazo.com/5cde5778749049ac232ca536b7b7d934.png
Runtime: https://i.gyazo.com/f9503890a42523d7ae150e02d18f1774.png

The picker renders 2 inputs where the hidden input automatically sets the current datetime as value. So in this situation my action will receive a value, even if the user does not enter a value in the runtime.

This behaviour does NOT seem to happen at the datePicker, only at the dateTimePicker so I expect it could be fixed quite easily :)

**Comment by chielwester** [comment]
Creating pull request
